---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: xray
  namespace: flux-system
spec:
  install:
    disableWait: true # don't wait for pod to be ready before applying changes
  upgrade:
    disableWait: true # don't wait for pod to be ready before applying changes
  interval: 1m0s
  releaseName: xray
  targetNamespace: default
  chart:
    spec:
      chart: xray
      version: 103.37.1
      sourceRef:
        kind: HelmRepository
        name: jfrog
  ###########################
  # Custom Xray values.yaml #
  ###########################
  values:
    rabbitmq:
      auth:
        password: f4PeLNdq25
    postgresql:
      postgresqlPassword: password
    xray:
      joinKey: 011b61f5c6a5928d4489df5fe6f120569c29c9e9dafb01f720c61853a3d90e2b
      masterKey: b46337c2a998d931246535fd2826928b83e3fb29bc4e5c8972c7c8e23f919b7c
      jfrogUrl: http://artifactory:8082
    unifiedUpgradeAllowed: true
    databaseUpgradeReady: true
  ###########################
